name: forecast-mae
phase: forecast

target:
  _target_: src.model.trainer_forecast.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  encoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
  interaction_type: ${interaction.type}
  interaction_radius: ${interaction.radius}
  interaction_max_neighbors: ${interaction.max_neighbors}
  interaction_dropout: ${interaction.dropout}
  interaction_num_layers: ${interaction.num_layers}
  interaction_stalk_dim: ${interaction.stalk_dim}
  interaction_q: ${interaction.q}
  interaction_lateral_threshold: ${interaction.lateral_threshold}
  interaction_ttc_threshold: ${interaction.ttc_threshold}
