name: forecast-mae
phase: forecast
monitor: val_b-minFDE6

target:
  _target_: src.model.trainer_forecast.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  encoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  winner_fde_weight: ${winner_fde_weight}
  endpoint_reg_weight: ${endpoint_reg_weight}
  other_loss_weight: ${other_loss_weight}
  probability_temperature: ${probability_temperature}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
