name: forecast-mae
phase: forecast
monitor: val_b-minFDE6

target:
  _target_: src.model.trainer_forecast.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  encoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  head_lr_scale: ${head_lr_scale}
  fde_loss_weight: ${fde_loss_weight}
  cls_temperature: ${cls_temperature}
  mr_loss_weight: ${mr_loss_weight}
  other_loss_weight: ${other_loss_weight}
  miss_threshold: ${miss_threshold}
  probability_temperature: ${probability_temperature}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
